# 事件配置文件
---
-
  Name: 前进两格
  Desc: 前进两格
  Method: Move
  Args: 
    step: 2
  Weight: 100
-
  Name: 前进一格
  Desc: 前进一格
  Method: Move
  Args: 
    step: 1
  Weight: 100
-
  Name: 后退两格
  Desc: 后退两格
  Method: Move
  Args: 
    step: -2
  Weight: 100
-
  Name: 后退一格
  Desc: 后退一格
  Method: Move
  Args: 
    step: -1
  Weight: 100
-
  Name: 回到起点
  Desc: 回到起点
  Method: BackStart
  Args: 
  Weight: 30
-
  Name: 路过的JayZ为你进行了一次狡辩
  Desc: 你的主被狡辩打动了，获得两回合惩罚数目减半。
  Method: AddBuff
  Args: 
    count: 2
    effect: 本次惩罚数目减半
  Weight: 100
-
  Name: net发现你半夜在水群，向你姐姐进行了揭发
  Desc: 你的姐姐非常生气，获得三回合惩罚额外增加20下小红
  Method: AddBuff
  Args: 
    count: 3
    effect: 增加20下小红
  Weight: 100
-
  Name: 路上遇见尼小诺并判定你的身体不适合继续惩罚
  Desc: 为了进行休养，获得两回合免去惩罚
  Method: AddBuff
  Args: 
    count: 2
    effect: 本回合免罚
  Weight: 100
-
  Name: 野生冰冰出没，她向你的主动安利了一系列工具 
  Desc: 下回合由主动指定追加一样工具，数量与主要惩罚相等
  Method: AddBuff
  Args: 
    count: 1
    effect: 本次惩罚主任意新增工具一件并惩罚相同数目
  Weight: 100
-
  Name: 和主动逛街，试衣服不耐烦
  Desc: 下次惩罚姿势改为镜前双手抱头
  Method: AddBuff
  Args: 
    count: 1
    effect: 本次惩罚姿势改为镜前双手抱头
  Weight: 100
-
  Name: Zara路过并对你进行了反主教导
  Desc: 由于工具被夺走，下回合只能使用手进行惩罚
  Method: AddBuff
  Args: 
    count: 1
    effect: 本次惩罚工具改为手
  Weight: 100
...