# 额外玩法配置文件
---
-
  Name: 正反报数
  Desc: 在打左边时进行正向报数，打右边时进行反向报数，出现错误则重来
  Weight: 50
-
  Name: 报质数
  Desc: 挨打时需要按顺序报出相应顺序的质数，报错重来
  Weight: 50
-
  Name: 静言
  Desc: 挨打时不能发出声音，否则重来
  Weight: 10
-
  Name: 木头人
  Desc: 挨打时不能动，否则重来
  Weight: 50
...